= Shortswords

The Copper Shortsword may be the most useless weapon in the game. Usually, a player immediately goes for a Wooden Sword or a Cactus Sword. This mod aims to make it more useful by making it the starting point for a line of shortswords, going to the Moon Lord and beyond.

== Upcoming Additions

* More shortswords: Copper/Tin, Iron/Lead, Tungsten/Silver, Gold/Platinum, Jungle, Dungeon, Demonite/Crimtane, Enchanted (Enchanted/Arkhalis), Meteor, Hellstone, Cobalt/Palladium, Mythril/Orichalcum, Titanium/Adamantite, Hallowed, True Hallowed (using Broken Hero Sword), Chlorophyte, Spectre (Ectoplasm), Halloween (Pumpkin Moon), Christmas (Frost Moon), Temple, Martian, Ocean (Duke Fishron), and maybe a few more
* Accessories that exclusively boost shortsword stats
* New sword-themed post-Moon Lord boss

== Changelog

v1.0.1
-----

* Added Solar Gauntlet; made from Fire Gauntlet and 8 Solar Fragments at an Ancient Manipulator; 2 defense, 16% increased melee damage + speed, inflicts Daybroken on hit
** Currently inflicts Daybroken on all types of damage, need to restrict it to melee

v1.0
-----

* Added Solar Stabber (post-Solar Pillar); made from 14 Solar Fragments at an Ancient Manipulator
* Added Lunar Lance (post-Moon Lord); made from a Solar Stabber and 8 Luminite Bars at an Ancient Manipulator
